Update trigger-terraform-apply.yml

diff --git a/.github/workflows/trigger-terraform-apply.yml b/.github/workflows/trigger-terraform-apply.yml
--- a/.github/workflows/trigger-terraform-apply.yml
+++ b/.github/workflows/trigger-terraform-apply.yml
@@ -122,8 +122,17 @@ jobs:
 
           echo "$VARS" | jq -r '.data[] | "TF_VAR_" + .attributes.key + "=" + .attributes.value' >> $GITHUB_ENV
 
+          # Extract subscription ID and set it as an environment variable
+          SUBSCRIPTION_ID=$(echo "$VARS" | jq -r '.data[] | select(.attributes.key == "sub") | .attributes.value')
+          echo "SUBSCRIPTION_ID=${SUBSCRIPTION_ID}" >> $GITHUB_ENV
+
       - name: Import JDiscord Extension
         run: |
+          if [ -z "$SUBSCRIPTION_ID" ]; then
+            echo "Error: Subscription ID is not set. Please ensure it's defined in your Terraform Cloud workspace."
+            exit 1
+          fi
+          
           terraform import \
           -var="azure_tenant_id=${TF_VAR_azure_tenant_id}" \
           -var="sub=${TF_VAR_sub}" \
@@ -135,7 +144,7 @@ jobs:
           -var="music_channel_id=${TF_VAR_music_channel_id}" \
           -var="discord_bot_owner=${TF_VAR_discord_bot_owner}" \
           module.jmusicbot.azurerm_virtual_machine_extension.run_jdiscordbot \
-          /subscriptions/${TF_VAR_sub}/resourceGroups/${AZURE_RESOURCE_GROUP}/providers/Microsoft.Compute/virtualMachines/${AZURE_VM_NAME}/extensions/run_jdiscordbot
+          "/subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${AZURE_RESOURCE_GROUP}/providers/Microsoft.Compute/virtualMachines/${AZURE_VM_NAME}/extensions/run_jdiscordbot"
 
       - name: Validate JMusicBot Jar File
         run: |
